/*                                                                             
               SAS DATA DEFINITION STATEMENTS FOR ICPSR 7419                   
                        SOUTHERN FARMS STUDY, 1860                             
                          DECEMBER 1976 VERSION                                
                                                                               
   The following SAS setup sections may appear in this file for the LRECL      
   version of this data collection.  These sections are listed below:          
                                                                               
   PROC FORMAT, in these statements, creates user-defined labels as            
   formats for variable values.   Formats replace original values with the     
   user-defined labels in subsequent SAS procedures once the formats           
   are assigned to a variable by the FORMAT command in the DATA step.          
   Not all variables necessarily have user-defined formats.                    
                                                                               
   DATA begins a SAS data step and names an output SAS dataset.                
                                                                               
   INFILE identifies the input file to be read with the input statement.       
   Users must replace the "file-specification" with host computer-specific     
   input file specifications.                                                  
                                                                               
   INPUT contains the SAS statements which assign the variable names and       
   specify the beginning and ending column locations in the LRECL data         
   file for each variable.                                                     
                                                                               
   LABEL assigns variable labels for all variables in the data file.           
   Variable labels and variable names may be identical for some data           
   files.                                                                      
                                                                               
   FORMAT in the SAS data step assigns the formats generated by the            
   PROC FORMAT procedure with the variable values in the SAS system file.      
   When SAS subsequently creates output, it utilizes the labels                
   found in the FORMAT rather than the raw data values.  NOTE: If a format     
   is assigned to a variable with a FORMAT statement, the values for           
   the variable are categorized by their labels *before* compilation and       
   printing by subsequent SAS procedures, i.e., values with identical          
   formats are treated as one group even though their values are               
   different.  Accordingly, users need to look at variable values before       
   jobs are run to assure that inadvertent grouping of results does not        
   occur.                                                                      
                                                                               
   MISSING VALUE RECODE sets user-defined numeric missing values to            
   missing as interpreted by the SAS system.  Only variables with              
   user-defined missing values are included in these statements.               
                                                                               
   Users may combine and modify these sections or parts of these sections      
   to suit their specific needs.  Users will also need to change the           
   file-specification in the INFILE statement to an appropriate filename       
   for their system.  Please note that the PROC FORMAT, FORMAT and             
   MISSING VALUE RECODE sections have been commented out (i.e., '/*').         
   To include the PROC FORMAT, FORMAT and MISSING VALUE RECODE sections        
   in the final SAS setup, remove the comment indicators from those            
   sections.                                                                   
                                                                               
**************************************************************************** */
                                                                               
* SAS DATA, INFILE, INPUT STATEMENTS;                                          
                                                                               
DATA;                                                                          
INFILE "file-specification" LRECL=1035;                                        
INPUT                                                                          
   V1 1-9                   V2 10-18                 V3 19-27                  
   V4 28-36                 V5 37-45                 V6 46-54                  
   V7 55-63                 V8 64-72                 V9 73-81                  
   V10 82-90                V11 91-99                V12 100-108               
   V13 109-117              V14 118-126              V15 127-135               
   V16 136-144              V17 145-153              V18 154-162               
   V19 163-171              V20 172-180              V21 181-189               
   V22 190-198              V23 199-207              V24 208-216               
   V25 217-225              V26 226-234              V27 235-243               
   V28 244-252              V29 253-261              V30 262-270               
   V31 271-279              V32 280-288              V33 289-297               
   V34 298-306              V35 307-315              V36 316-324               
   V37 325-333              V38 334-342              V39 343-351               
   V40 352-360              V41 361-369              V42 370-378               
   V43 379-387              V44 388-396              V45 397-405               
   V46 406-414              V47 415-423              V48 424-432               
   V49 433-441              V50 442-450              V51 451-459               
   V52 460-468              V53 469-477              V54 478-486               
   V55 487-489              V56 490-492              V57 493-495               
   V58 496-498              V59 499-501              V60 502-504               
   V61 505-507              V62 508-510              V63 511-513               
   V64 514-516              V65 517-519              V66 520-522               
   V67 523-525              V68 526-528              V69 529-531               
   V70 532-534              V71 535-537              V72 538-540               
   V73 541-543              V74 544-546              V75 547-549               
   V76 550-552              V77 553-555              V78 556-558               
   V79 559-561              V80 562-564              V81 565-567               
   V82 568-570              V83 571-573              V84 574-576               
   V85 577-579              V86 580-582              V87 583-585               
   V88 586-588              V89 589-591              V90 592-594               
   V91 595-597              V92 598-600              V93 601-603               
   V94 604-606              V95 607-609              V96 610-612               
   V97 613-615              V98 616-618              V99 619-621               
   V100 622-624             V101 625-627             V102 628-630              
   V103 631-633             V104 634-636             V105 637-639              
   V106 640-642             V107 643-645             V108 646-648              
   V109 649-651             V110 652-654             V111 655-657              
   V112 658-660             V113 661-663             V114 664-666              
   V115 667-669             V116 670-672             V117 673-675              
   V118 676-678             V119 679-681             V120 682-684              
   V121 685-687             V122 688-690             V123 691-693              
   V124 694-696             V125 697-699             V126 700-702              
   V127 703-705             V128 706-708             V129 709-711              
   V130 712-714             V131 715-717             V132 718-720              
   V133 721-723             V134 724-726             V135 727-729              
   V136 730-732             V137 733-735             V138 736-738              
   V139 739-741             V140 742-744             V141 745-747              
   V142 748-750             V143 751-753             V144 754-756              
   V145 757-759             V146 760-762             V147 763-765              
   V148 766-768             V149 769-771             V150 772-774              
   V151 775-777             V152 778-780             V153 781-783              
   V154 784-786             V155 787-789             V156 790-792              
   V157 793-795             V158 796-798             V159 799-801              
   V160 802-804             V161 805-807             V162 808-810              
   V163 811-813             V164 814-816             V165 817-819              
   V166 820-822             V167 823-825             V168 826-828              
   V169 829-831             V170 832-834             V171 835-837              
   V172 838-840             V173 841-843             V174 844-846              
   V175 847-849             V176 850-852             V177 853-855              
   V178 856-858             V179 859-861             V180 862-864              
   V181 865-867             V182 868-870             V183 871-873              
   V184 874-876             V185 877-879             V186 880-882              
   V187 883-885             V188 886-888             V189 889-891              
   V190 892-894             V191 895-897             V192 898-900              
   V193 901-903             V194 904-906             V195 907-909              
   V196 910-912             V197 913-915             V198 916-918              
   V199 919-921             V200 922-924             V201 925-927              
   V202 928-930             V203 931-933             V204 934-936              
   V205 937-939             V206 940-942             V207 943-945              
   V208 946-948             V209 949-951             V210 952-954              
   V211 955-957             V212 958-960             V213 961-963              
   V214 964-966             V215 967-969             V216 970-972              
   V217 973-975             V218 976-978             V219 979-981              
   V220 982-984             V221 985-987             V222 988-990              
   V223 991-993             V224 994-996             V225 997-999              
   V226 1000-1002           V227 1003-1005           V228 1006-1008            
   V229 1009-1011           V230 1012-1014           V231 1015-1017            
   V232 1018-1020           V233 1021-1023           V234 1024-1026            
   V235 1027-1031           V236 1032-1035;                                    
                                                                               
* SAS LABEL STATEMENT;                                                         
                                                                               
LABEL                                                                          
   V1 = "COUNTY NUMBER"                                                        
   V2 = "SOIL TYPE CODE"                                                       
   V3 = "NUMBER OF FARMS SAMPLED"                                              
   V4 = "COUNTY COTTON PRODUCTION"                                             
   V5 = "PAGE-LINE CODE"                                                       
   V6 = "VALUE OF PERSONAL PROP"                                               
   V7 = "ACRES OF IMPROVED LAND"                                               
   V8 = "ACRES OF UNIMPROVED LAND"                                             
   V9 = "$ VALUE OF FARM"                                                      
   V10 = "$ VALUE FARM MACHINERY"                                              
   V11 = "# HEAD OF HORSES"                                                    
   V12 = "# HEAD OF ASSES AND MULES"                                           
   V13 = "# HEAD OF MILK COWS"                                                 
   V14 = "# HEAD OF WORKING OXEN"                                              
   V15 = "# HEAD OF OTHER CATTLE"                                              
   V16 = "# HEAD OF SHEEP"                                                     
   V17 = "# HEAD OF SWINE"                                                     
   V18 = "$ VALUE OF LIVESTOCK"                                                
   V19 = "BUSHELS OF WHEAT"                                                    
   V20 = "BUSHELS OF RYE"                                                      
   V21 = "BUSHELS OF CORN"                                                     
   V22 = "BUSHELS OF OATS"                                                     
   V23 = "BUSHELS OF RICE"                                                     
   V24 = "POUNDS OF TOBACCO"                                                   
   V25 = "BALES OF COTTON"                                                     
   V26 = "POUNDS OF WOOL"                                                      
   V27 = "BUSHELS OF PEAS AND BEANS"                                           
   V28 = "BUSHELS OF IRISH POTATO"                                             
   V29 = "BUSHELS OF SWEET POTATO"                                             
   V30 = "BUSHELS OF BARLEY"                                                   
   V31 = "BUSHELS OF BUCKWHEAT"                                                
   V32 = "$ VALUE  ORCHARD PRODUCT"                                            
   V33 = "GALLONS OF WINE"                                                     
   V34 = "$ VAL OF MKT GARDEN PROD"                                            
   V35 = "POUNDS OF BUTTER"                                                    
   V36 = "POUNDS OF CHEESE"                                                    
   V37 = "TONS OF HAY AND FODDER"                                              
   V38 = "BUSHELS OF CLOVER SEED"                                              
   V39 = "BUSHELS OF GRASS SEED"                                               
   V40 = "POUNDS OF HOPS"                                                      
   V41 = "TONS OF DEW ROTTED HEMP"                                             
   V42 = "TONS OF WAT ROTTED HEMP"                                             
   V43 = "TONS OF OTHER HEMP"                                                  
   V44 = "POUNDS OF FLAX"                                                      
   V45 = "BUSHELS OF FLAXSEED"                                                 
   V46 = "POUNDS OF SILK COCOONS"                                              
   V47 = "POUNDS OF MAPLE SUGAR"                                               
   V48 = "1000 POUNDS-CANE SUGAR"                                              
   V49 = "GALLONS OF MOLASSES"                                                 
   V50 = "POUNDS OF BEESWAX"                                                   
   V51 = "POUNDS OF HONEY"                                                     
   V52 = "$ VALUE OF HOME MANUF"                                               
   V53 = "$ VALUE OF ANIMAL SLAUGH"                                            
   V54 = "CHECK TOTAL FOR ABOVE"                                               
   V55 = "FREE MALES LESS THAN 6MO"                                            
   V56 = "FREE MALES  1 - 4"                                                   
   V57 = "FREE MALES  5 - 9"                                                   
   V58 = "FREE MALES 10 - 14"                                                  
   V59 = "FREE MALES 15 - 19"                                                  
   V60 = "FREE MALES 20 - 24"                                                  
   V61 = "FREE MALES 25 - 29"                                                  
   V62 = "FREE MALES 30 - 34"                                                  
   V63 = "FREE MALES 35 - 39"                                                  
   V64 = "FREE MALES 40 - 44"                                                  
   V65 = "FREE MALES 45 - 49"                                                  
   V66 = "FREE MALES 50 - 54"                                                  
   V67 = "FREE MALES 55 - 59"                                                  
   V68 = "FREE MALES 60 - 64"                                                  
   V69 = "FREE MALES 65 - 69"                                                  
   V70 = "FREE MALES 70 - 79"                                                  
   V71 = "FREE MALES 80 - 89"                                                  
   V72 = "FREE MALES 90 AND OVER"                                              
   V73 = "FREE FEMALES LESS THAN6M"                                            
   V74 = "FREE FEMALES  1 -  4"                                                
   V75 = "FREE FEMALES  5 -  9"                                                
   V76 = "FREE FEMALES 10 - 14"                                                
   V77 = "FREE FEMALES 15 - 19"                                                
   V78 = "FREE FEMALES 20 - 24"                                                
   V79 = "FREE FEMALES 25 - 29"                                                
   V80 = "FREE FEMALES 30 - 34"                                                
   V81 = "FREE FEMALES 35 - 39"                                                
   V82 = "FREE FEMALES 40 - 44"                                                
   V83 = "FREE FEMALES 45 - 49"                                                
   V84 = "FREE FEMALES 50 - 54"                                                
   V85 = "FREE FEMALES 55 - 59"                                                
   V86 = "FREE FEMALES 60 - 64"                                                
   V87 = "FREE FEMALES 65 - 69"                                                
   V88 = "FREE FEMALES 70 - 79"                                                
   V89 = "FREE FEMALES 80 - 89"                                                
   V90 = "FREE FEMALES 90 AND OVER"                                            
   V91 = "SLAVE MALE LESS THAN 6MO"                                            
   V92 = "SLAVE MALE  1 -  4"                                                  
   V93 = "SLAVE MALE  5 -  9"                                                  
   V94 = "SLAVE MALE 10 - 14"                                                  
   V95 = "SLAVE MALE 15 - 19"                                                  
   V96 = "SLAVE MALE 20 -24”"                                                  
   V97 = "SLAVE MALE 25 - 29"                                                  
   V98 = "SLAVE MALE 30 - 34"                                                  
   V99 = "SLAVE MALE 35 - 39"                                                  
   V100 = "MALE SLAVE 40 - 44"                                                 
   V101 = "SLAVE MALE 45 - 49"                                                 
   V102 = "SLAVE MALE 50 - 54"                                                 
   V103 = "SLAVE MALE 55 - 59"                                                 
   V104 = "SLAVE MALE 60 - 64"                                                 
   V105 = "SLAVE MALE 65 - 69"                                                 
   V106 = "SLAVE MALE 70 - 79"                                                 
   V107 = "MALE SLAVE 80 - 89"                                                 
   V108 = "SLAVE MALE 90 AND OVER"                                             
   V109 = "SLAVE FEMALE LESS THAN6M"                                           
   V110 = "SLAVE FEMALE  1 - 4"                                                
   V111 = "SLAVE FEMALE  5 - 9"                                                
   V112 = "SLAVE FEMALE 10 - 14"                                               
   V113 = "SLAVE FEMALE 15 - 19"                                               
   V114 = "SLAVE FEMALE 20 - 24"                                               
   V115 = "SLAVE FEMALE 25 - 29"                                               
   V116 = "SLAVE FEMALE 30 - 34"                                               
   V117 = "SLAVE FEMALE 35 - 39"                                               
   V118 = "SLAVE FEMALE 40 - 44"                                               
   V119 = "SLAVE FEMALE 45 - 49"                                               
   V120 = "SLAVE FEMALE 50 - 54"                                               
   V121 = "SLAVE FEMALE 55 - 59"                                               
   V122 = "SLAVE FEMALE 60 - 64"                                               
   V123 = "SLAVE FEMALE 65 - 69"                                               
   V124 = "SLAVE FEMALE 70 - 79"                                               
   V125 = "SLAVE FEMALE 80 - 89"                                               
   V126 = "SLAVE FEMALE 90 AND OVER"                                           
   V127 = "MALE FARM LABORER  6MO"                                             
   V128 = "MALE FARM LABORER  1-4"                                             
   V129 = "MALE FARM LABORER  5-9"                                             
   V130 = "MALE FARM LABORER 10-14"                                            
   V131 = "MALE FARM LABORER 15-19"                                            
   V132 = "MALE FARM LABORER 20-24"                                            
   V133 = "MALE FARM LABORER 25-29"                                            
   V134 = "MALE FARM LABORER 30-34"                                            
   V135 = "MALE FARM LABORER 35-39"                                            
   V136 = "MALE FARM LABORER 40-44"                                            
   V137 = "MALE FARM LABORER 45-49"                                            
   V138 = "MALE FARM LABORER 50-54"                                            
   V139 = "MALE FARM LABORER 55-59"                                            
   V140 = "MALE FARM LABORER 60-64"                                            
   V141 = "MALE FARM LABORER 65-69"                                            
   V142 = "MALE FARM LABORER 70-79"                                            
   V143 = "MALE FARM LABORER 80-89"                                            
   V144 = "MALE FARM LABORER 90 AND UP"                                        
   V145 = "FEMALE FARM LAB LESS 6MO"                                           
   V146 = "FEMALE FARM LAB  1 - 4"                                             
   V147 = "FEMALE FARM LAB  5 - 9"                                             
   V148 = "FEMALE FARM LAB 10 - 14"                                            
   V149 = "FEMALE FARM LAB 15 - 19"                                            
   V150 = "FEMALE FARM LAB 20 - 24"                                            
   V151 = "FEMALE FARM LAB 25 - 29"                                            
   V152 = "FEMALE FARM LAB 30 - 34"                                            
   V153 = "FEMALE FARM LAB 35 - 39"                                            
   V154 = "FEMALE FARM LAB 40 - 44"                                            
   V155 = "FEMALE FARM LAB 45 - 49"                                            
   V156 = "FEMALE FARM LAB 50 - 54"                                            
   V157 = "FEMALE FARM LAB 55 - 59"                                            
   V158 = "FEMALE FARM LAB 60 - 64"                                            
   V159 = "FEMALE FARM LAB 65 - 69"                                            
   V160 = "FEMALE FARM LAB 70 - 79"                                            
   V161 = "FEMALE FARM LAB 80 - 89"                                            
   V162 = "FEMALE FARM LAB 90 AND UP"                                          
   V163 = "MALE OVERSEER LESS 6MO"                                             
   V164 = "MALE OVERSEER  1 - 4"                                               
   V165 = "MALE OVERSEER  5 - 9"                                               
   V166 = "MALE OVERSEER 10 - 14"                                              
   V167 = "MALE OVERSEER 15 - 19"                                              
   V168 = "MALE OVERSEER 20 - 24"                                              
   V169 = "MALE OVERSEER 25 - 29"                                              
   V170 = "MALE OVERSEER 30 - 34"                                              
   V171 = "MALE OVERSEER 35 - 39"                                              
   V172 = "MALE OVERSEER 40 - 44"                                              
   V173 = "MALE OVERSEER 45 - 49"                                              
   V174 = "MALE OVERSEER 50 - 54"                                              
   V175 = "MALE OVERSEER 55 - 59"                                              
   V176 = "MALE OVERSEER 60 - 64"                                              
   V177 = "MALE OVERSEER 65 - 69"                                              
   V178 = "MALE OVERSEER 70 - 79"                                              
   V179 = "MALE OVERSEER 80 - 89"                                              
   V180 = "MALE OVERSEER 90 AND OVER"                                          
   V181 = "FEMALE OVERSEER LESS 6MO"                                           
   V182 = "FEMALE OVERSEER  1 - 4"                                             
   V183 = "FEMALE OVERSEER  5 - 9"                                             
   V184 = "FEMALE OVERSEER 10 - 14"                                            
   V185 = "FEMALE OVERSEER 15 - 19"                                            
   V186 = "FEMALE OVERSEER 20 - 24"                                            
   V187 = "FEMALE OVERSEER 25 - 29"                                            
   V188 = "FEMALE OVERSEER 30 - 34"                                            
   V189 = "FEMALE OVERSEER 35 - 39"                                            
   V190 = "FEMALE OVERSEER 40 - 44"                                            
   V191 = "FEMALE OVERSEER 45 - 49"                                            
   V192 = "FEMALE OVERSEER 50 - 54"                                            
   V193 = "FEMALE OVERSEER 55 - 59"                                            
   V194 = "FEMALE OVERSEER 60 - 64"                                            
   V195 = "FEMALE OVERSEER 65 - 69"                                            
   V196 = "FEMALE OVERSEER 70 - 79"                                            
   V197 = "FEMALE OVERSEER 80 - 89"                                            
   V198 = "FEMALE OVERSEER 90 AND UP"                                          
   V199 = "MALE NONFARM WKS LESS 6M"                                           
   V200 = "MALE NONFARM WKS  1 - 4"                                            
   V201 = "MALE NONFARM WKS  5 - 9"                                            
   V202 = "MALE NONFARM WKS 10 - 14"                                           
   V203 = "MALE NONFARM WKS 15 - 19"                                           
   V204 = "MALE NONFARM WKS 20 - 24"                                           
   V205 = "MALE NONFARM WKS 25 - 29"                                           
   V206 = "MALE NONFARM WKS 30 - 34"                                           
   V207 = "MALE NONFARM WKS 35 - 39"                                           
   V208 = "MALE NONFARM WKS 40 - 44"                                           
   V209 = "MALE NONFARM WKS 45 - 49"                                           
   V210 = "MALE NONFARM WKS 50 - 54"                                           
   V211 = "MALE NONFARM WKS 55 - 59"                                           
   V212 = "MALE NONFARM WKS 60 - 64"                                           
   V213 = "MALE NONFARM WKS 65 - 69"                                           
   V214 = "MALE NONFARM WKS 70 - 79"                                           
   V215 = "MALE NONFARM WKS 80 - 89"                                           
   V216 = "MALE NONFARM WKS 90 AND UP"                                         
   V217 = "FEMALE NONFARM WKS LESS"                                            
   V218 = "FEMALE NONFARM WKS  1-4"                                            
   V219 = "FEMALE NONFARM WKS  5-9"                                            
   V220 = "FEMALE NONFARM WKS 10-14"                                           
   V221 = "FEMALE NONFARM WKS 15-19"                                           
   V222 = "FEMALE NONFARM WKS 20-24"                                           
   V223 = "FEMALE NONFARM WKS 25-29"                                           
   V224 = "FEMALE NONFARM WKS 30-34"                                           
   V225 = "FEMALE NONFARM WKS 35-39"                                           
   V226 = "FEMALE NONFARM WKS 40-44"                                           
   V227 = "FEMALE NONFARM WKS 45-49"                                           
   V228 = "FEMALE NONFARM WKS 50-54"                                           
   V229 = "FEMALE NONFARM WKS 55-59"                                           
   V230 = "FEMALE NONFARM WKS 60-64"                                           
   V231 = "FEMALE NONFARM WKS 65-69"                                           
   V232 = "FEMALE NONFARM WKS 70-79"                                           
   V233 = "FEMALE NONFARM WKS 80-89"                                           
   V234 = "FEMALE NONFARM WKS 90 AND UP"                                       
   V235 = "TOTAL POPULATION"                                                   
   V236 = "FARM SEQUENCE NUMBER";                                              
                                                                               
* USER-DEFINED MISSING VALUE RECODE TO SAS SYSMIS;                             
                                                                               
/*                                                                             
   IF V1=9999999 THEN V1=.;            IF V2=9999999 THEN V2=.;                
   IF V3=9999999 THEN V3=.;            IF V4=9999999 THEN V4=.;                
   IF V5=9999999 THEN V5=.;            IF V6=9999999 THEN V6=.;                
   IF V7=9999999 THEN V7=.;            IF V8=9999999 THEN V8=.;                
   IF V9=9999999 THEN V9=.;            IF V10=9999999 THEN V10=.;              
   IF V11=9999999 THEN V11=.;          IF V12=9999999 THEN V12=.;              
   IF V13=9999999 THEN V13=.;          IF V14=9999999 THEN V14=.;              
   IF V15=9999999 THEN V15=.;          IF V16=9999999 THEN V16=.;              
   IF V17=9999999 THEN V17=.;          IF V18=9999999 THEN V18=.;              
   IF V19=9999999 THEN V19=.;          IF V20=9999999 THEN V20=.;              
   IF V21=9999999 THEN V21=.;          IF V22=9999999 THEN V22=.;              
   IF V23=9999999 THEN V23=.;          IF V24=9999999 THEN V24=.;              
   IF V25=9999999 THEN V25=.;          IF V26=9999999 THEN V26=.;              
   IF V27=9999999 THEN V27=.;          IF V28=9999999 THEN V28=.;              
   IF V29=9999999 THEN V29=.;          IF V30=9999999 THEN V30=.;              
   IF V31=9999999 THEN V31=.;          IF V32=9999999 THEN V32=.;              
   IF V33=9999999 THEN V33=.;          IF V34=9999999 THEN V34=.;              
   IF V35=9999999 THEN V35=.;          IF V36=9999999 THEN V36=.;              
   IF V37=9999999 THEN V37=.;          IF V38=9999999 THEN V38=.;              
   IF V39=9999999 THEN V39=.;          IF V40=9999999 THEN V40=.;              
   IF V41=9999999 THEN V41=.;          IF V42=9999999 THEN V42=.;              
   IF V43=9999999 THEN V43=.;          IF V44=9999999 THEN V44=.;              
   IF V45=9999999 THEN V45=.;          IF V46=9999999 THEN V46=.;              
   IF V47=9999999 THEN V47=.;          IF V48=9999999 THEN V48=.;              
   IF V49=9999999 THEN V49=.;          IF V50=9999999 THEN V50=.;              
   IF V51=9999999 THEN V51=.;          IF V52=9999999 THEN V52=.;              
   IF V53=9999999 THEN V53=.;          IF V54=9999999 THEN V54=.;              
   IF V55=0000999 THEN V55=.;          IF V56=0000999 THEN V56=.;              
   IF V57=0000999 THEN V57=.;          IF V58=0000999 THEN V58=.;              
   IF V59=0000999 THEN V59=.;          IF V60=0000999 THEN V60=.;              
   IF V61=0000999 THEN V61=.;          IF V62=0000999 THEN V62=.;              
   IF V63=0000999 THEN V63=.;          IF V64=0000999 THEN V64=.;              
   IF V65=0000999 THEN V65=.;          IF V66=0000999 THEN V66=.;              
   IF V67=0000999 THEN V67=.;          IF V68=0000999 THEN V68=.;              
   IF V69=0000999 THEN V69=.;          IF V70=0000999 THEN V70=.;              
   IF V71=0000999 THEN V71=.;          IF V72=0000999 THEN V72=.;              
   IF V73=0000999 THEN V73=.;          IF V74=0000999 THEN V74=.;              
   IF V75=0000999 THEN V75=.;          IF V76=0000999 THEN V76=.;              
   IF V77=0000999 THEN V77=.;          IF V78=0000999 THEN V78=.;              
   IF V79=0000999 THEN V79=.;          IF V80=0000999 THEN V80=.;              
   IF V81=0000999 THEN V81=.;          IF V82=0000999 THEN V82=.;              
   IF V83=0000999 THEN V83=.;          IF V84=0000999 THEN V84=.;              
   IF V85=0000999 THEN V85=.;          IF V86=0000999 THEN V86=.;              
   IF V87=0000999 THEN V87=.;          IF V88=0000999 THEN V88=.;              
   IF V89=0000999 THEN V89=.;          IF V90=0000999 THEN V90=.;              
   IF V91=0000999 THEN V91=.;          IF V92=0000999 THEN V92=.;              
   IF V93=0000999 THEN V93=.;          IF V94=0000999 THEN V94=.;              
   IF V95=0000999 THEN V95=.;          IF V96=0000999 THEN V96=.;              
   IF V97=0000999 THEN V97=.;          IF V98=0000999 THEN V98=.;              
   IF V99=0000999 THEN V99=.;          IF V100=0000999 THEN V100=.;            
   IF V101=0000999 THEN V101=.;        IF V102=0000999 THEN V102=.;            
   IF V103=0000999 THEN V103=.;        IF V104=0000999 THEN V104=.;            
   IF V105=0000999 THEN V105=.;        IF V106=0000999 THEN V106=.;            
   IF V107=0000999 THEN V107=.;        IF V108=0000999 THEN V108=.;            
   IF V109=0000999 THEN V109=.;        IF V110=0000999 THEN V110=.;            
   IF V111=0000999 THEN V111=.;        IF V112=0000999 THEN V112=.;            
   IF V113=0000999 THEN V113=.;        IF V114=0000999 THEN V114=.;            
   IF V115=0000999 THEN V115=.;        IF V116=0000999 THEN V116=.;            
   IF V117=0000999 THEN V117=.;        IF V118=0000999 THEN V118=.;            
   IF V119=0000999 THEN V119=.;        IF V120=0000999 THEN V120=.;            
   IF V121=0000999 THEN V121=.;        IF V122=0000999 THEN V122=.;            
   IF V123=0000999 THEN V123=.;        IF V124=0000999 THEN V124=.;            
   IF V125=0000999 THEN V125=.;        IF V126=0000999 THEN V126=.;            
   IF V127=0000999 THEN V127=.;        IF V128=0000999 THEN V128=.;            
   IF V129=0000999 THEN V129=.;        IF V130=0000999 THEN V130=.;            
   IF V131=0000999 THEN V131=.;        IF V132=0000999 THEN V132=.;            
   IF V133=0000999 THEN V133=.;        IF V134=0000999 THEN V134=.;            
   IF V135=0000999 THEN V135=.;        IF V136=0000999 THEN V136=.;            
   IF V137=0000999 THEN V137=.;        IF V138=0000999 THEN V138=.;            
   IF V139=0000999 THEN V139=.;        IF V140=0000999 THEN V140=.;            
   IF V141=0000999 THEN V141=.;        IF V142=0000999 THEN V142=.;            
   IF V143=0000999 THEN V143=.;        IF V144=0000999 THEN V144=.;            
   IF V145=0000999 THEN V145=.;        IF V146=0000999 THEN V146=.;            
   IF V147=0000999 THEN V147=.;        IF V148=0000999 THEN V148=.;            
   IF V149=0000999 THEN V149=.;        IF V150=0000999 THEN V150=.;            
   IF V151=0000999 THEN V151=.;        IF V152=0000999 THEN V152=.;            
   IF V153=0000999 THEN V153=.;        IF V154=0000999 THEN V154=.;            
   IF V155=0000999 THEN V155=.;        IF V156=0000999 THEN V156=.;            
   IF V157=0000999 THEN V157=.;        IF V158=0000999 THEN V158=.;            
   IF V159=0000999 THEN V159=.;        IF V160=0000999 THEN V160=.;            
   IF V161=0000999 THEN V161=.;        IF V162=0000999 THEN V162=.;            
   IF V163=0000999 THEN V163=.;        IF V164=0000999 THEN V164=.;            
   IF V165=0000999 THEN V165=.;        IF V166=0000999 THEN V166=.;            
   IF V167=0000999 THEN V167=.;        IF V168=0000999 THEN V168=.;            
   IF V169=0000999 THEN V169=.;        IF V170=0000999 THEN V170=.;            
   IF V171=0000999 THEN V171=.;        IF V172=0000999 THEN V172=.;            
   IF V173=0000999 THEN V173=.;        IF V174=0000999 THEN V174=.;            
   IF V175=0000999 THEN V175=.;        IF V176=0000999 THEN V176=.;            
   IF V177=0000999 THEN V177=.;        IF V178=0000999 THEN V178=.;            
   IF V179=0000999 THEN V179=.;        IF V180=0000999 THEN V180=.;            
   IF V181=0000999 THEN V181=.;        IF V182=0000999 THEN V182=.;            
   IF V183=0000999 THEN V183=.;        IF V184=0000999 THEN V184=.;            
   IF V185=0000999 THEN V185=.;        IF V186=0000999 THEN V186=.;            
   IF V187=0000999 THEN V187=.;        IF V188=0000999 THEN V188=.;            
   IF V189=0000999 THEN V189=.;        IF V190=0000999 THEN V190=.;            
   IF V191=0000999 THEN V191=.;        IF V192=0000999 THEN V192=.;            
   IF V193=0000999 THEN V193=.;        IF V194=0000999 THEN V194=.;            
   IF V195=0000999 THEN V195=.;        IF V196=0000999 THEN V196=.;            
   IF V197=0000999 THEN V197=.;        IF V198=0000999 THEN V198=.;            
   IF V199=0000999 THEN V199=.;        IF V200=0000999 THEN V200=.;            
   IF V201=0000999 THEN V201=.;        IF V202=0000999 THEN V202=.;            
   IF V203=0000999 THEN V203=.;        IF V204=0000999 THEN V204=.;            
   IF V205=0000999 THEN V205=.;        IF V206=0000999 THEN V206=.;            
   IF V207=0000999 THEN V207=.;        IF V208=0000999 THEN V208=.;            
   IF V209=0000999 THEN V209=.;        IF V210=0000999 THEN V210=.;            
   IF V211=0000999 THEN V211=.;        IF V212=0000999 THEN V212=.;            
   IF V213=0000999 THEN V213=.;        IF V214=0000999 THEN V214=.;            
   IF V215=0000999 THEN V215=.;        IF V216=0000999 THEN V216=.;            
   IF V217=0000999 THEN V217=.;        IF V218=0000999 THEN V218=.;            
   IF V219=0000999 THEN V219=.;        IF V220=0000999 THEN V220=.;            
   IF V221=0000999 THEN V221=.;        IF V222=0000999 THEN V222=.;            
   IF V223=0000999 THEN V223=.;        IF V224=0000999 THEN V224=.;            
   IF V225=0000999 THEN V225=.;        IF V226=0000999 THEN V226=.;            
   IF V227=0000999 THEN V227=.;        IF V228=0000999 THEN V228=.;            
   IF V229=0000999 THEN V229=.;        IF V230=0000999 THEN V230=.;            
   IF V231=0000999 THEN V231=.;        IF V232=0000999 THEN V232=.;            
   IF V233=0000999 THEN V233=.;        IF V234=0000999 THEN V234=.;            
   IF V235=0099999 THEN V235=.;        IF V236=0009999 THEN V236=.;            
                                                                               
*/                                                                             
